### ISSUE TITLE
Quick Start example doesn't seem to be working

### ISSUE THREAD

**Issue by thiagomajesk** [HugoDF/alpine-test-utils#15]
Just tested the quick start example and it doesn't seem to be working for me:

```
test('test foo component', () => {
        const componentHtml = `<div x-data="{foo: 'bar'}">
          <span x-text="foo"></span>
        </div>`
        const component = render(componentHtml);
        expect(component.querySelector('span').innerText).toEqual('bar');
      });
```

This is what I get:

```
    expect(received).toEqual(expected) // deep equality

    Expected: "bar"
    Received: undefined

      40 |         </div>`
      41 |         const component = render(componentHtml);
    > 42 |         expect(component.querySelector('span').innerText).toEqual('bar');
         |                                                           ^
      43 |       });
      44 | })

      at Object.<anonymous> (js/test/item-selection.test.js:42:59)

Test Suites: 1 failed, 1 passed, 2 total
Tests:       1 failed, 8 passed, 9 total
Snapshots:   0 total
Time:        4.353s
Ran all test suites matching /assets\\js\\test/i.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ test: `jest assets/js/test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\{user}\AppData\Roaming\npm-cache\_logs\2020-06-17T18_35_26_210Z-debug.log
```

Is there something I'm missing out? 
I've tested with both Nodejs 14 (latest) and 12 (stable) on Windows and MacOs respectively.
I'm also using  Jest version "^25.1.0".

**Comment by HugoDF** [comment]
Interesting, I haven't actually tested this with Jest, will look into it

**Comment by thiagomajesk** [comment]
@HugoDF Thanks for the quick reply.
I'm currently using something like the approach bellow to test other components:
 
```javascript
import { waitFor, fireEvent } from '@testing-library/dom'

test('test somethin', async () => {
    document.body.innerHTML = `component html`
    
    Alpine.start()
            
    await waitFor(() => {
        expect(someReturn).toEqual(somethingExpected)
    })
}
```

Which is a very "native" approach, and works fine. But I was looking to improve readability with this lib 😄. Tell me if there is something that I could do to help.

Best regards!

**Comment by HugoDF** [comment]
@thiagomajesk yeah, my bad to be fair I didn't check Jest compatibility.

Since I built the lib to write tests with AVA 😄. PR is up now and will be released shortly

**Comment by HugoDF** [comment]
Ok @thiagomajesk try latest, should fix quickstart example with Jest.

Feel free to open issues, I think I should add something like `waitFor`, although you can work around things for now by using `component.$nextTick()`
